//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatNav.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingAssetPackage
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string MAPName { get; set; }
        public string Problem { get; set; }
        public string ProblemValidation { get; set; }
        public string Hypothesis { get; set; }
        public string Notes { get; set; }
        public int PackageContainerId { get; set; }
    
        public virtual PackageContainer PackageContainer { get; set; }
    }
}
