//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatNav.DAL
{
    using StatNav.DAL.Repositories;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StatNavDBEntities : DbContext
    {
        public StatNavDBEntities()
            : base(StatNavDBConfig.StatNavDBConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MarketingAssetPackage> MarketingAssetPackages { get; set; }
        public virtual DbSet<PackageContainer> PackageContainers { get; set; }
    }
}
