// <auto-generated />
namespace StatNav.WebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CandidateTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CandidateTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201912200830429_CandidateTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
