// <auto-generated />
namespace StatNav.WebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _2069RemoveAttributesFromMAPEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2069RemoveAttributesFromMAPEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202006151341323_2069RemoveAttributesFromMAPEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
