// <auto-generated />
namespace StatNav.WebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _2067StagesTableEdit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2067StagesTableEdit));
        
        string IMigrationMetadata.Id
        {
            get { return "202006111300406_2067StagesTableEdit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
