// <auto-generated />
namespace StatNav.WebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Story2071CandidateToVariant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Story2071CandidateToVariant));
        
        string IMigrationMetadata.Id
        {
            get { return "202007021317592_Story2071CandidateToVariant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
